// All 30 programmatic pages from the CSV + extras
export const PAGES_DATA = {
  "ai-marketing-agent-for-restaurants": {
    slug: "ai-marketing-agent-for-restaurants",
    keyword: "AI marketing agent for restaurants",
    title: "AI Marketing Agent for Restaurants",
    h1: "Fill tables with campaigns built in minutes",
    audience: "Restaurants",
    industry: "restaurants",
    pain: "Restaurant marketing moves fast. A lunch special, holiday menu, or empty Tuesday night cannot wait two weeks for a campaign. Buildo gives owners and managers a fast way to create polished marketing without starting from a blank page.",
    cta: "Build my restaurant campaign",
    useCases: ["Promote weekly specials", "Fill slow nights", "Announce events", "Drive reservations", "Re-engage previous customers"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
      { label: "Buildo vs ChatGPT", href: "/buildo-vs-chatgpt" },
    ],
  },
  "facebook-ads-automation-for-restaurants": {
    slug: "facebook-ads-automation-for-restaurants",
    keyword: "Facebook ads automation for restaurants",
    title: "Facebook Ads Automation for Restaurants",
    h1: "Launch restaurant promos without an agency",
    audience: "Restaurants",
    industry: "restaurants",
    pain: "Agency retainers are expensive for simple promotions",
    cta: "Create my first ad",
    useCases: ["Weekly specials", "Event promotions", "Delivery offers", "Happy hour ads"],
    relatedLinks: [
      { label: "AI Marketing Agent for Restaurants", href: "/ai-marketing-agent-for-restaurants" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "whatsapp-marketing-for-restaurants": {
    slug: "whatsapp-marketing-for-restaurants",
    keyword: "WhatsApp marketing for restaurants",
    title: "WhatsApp Marketing for Restaurants",
    h1: "Turn repeat customers into weekly bookings",
    audience: "Restaurants",
    industry: "restaurants",
    pain: "Customers forget specials and events",
    cta: "Create WhatsApp campaign",
    useCases: ["Reminder messages", "Reservation follow-ups", "Special offer broadcasts", "Loyalty programs"],
    relatedLinks: [
      { label: "AI Marketing Agent for Restaurants", href: "/ai-marketing-agent-for-restaurants" },
      { label: "WhatsApp Campaign Generator", href: "/tools/whatsapp-campaign-generator" },
    ],
  },
  "ai-marketing-agent-for-real-estate": {
    slug: "ai-marketing-agent-for-real-estate",
    keyword: "AI marketing agent for real estate agents",
    title: "AI Marketing Agent for Real Estate Agents",
    h1: "Create listing campaigns before the next showing",
    audience: "Real estate agents",
    industry: "real-estate",
    pain: "Listings need fast promotion across channels",
    cta: "Promote a listing",
    useCases: ["New listing announcements", "Open house promotions", "Buyer lead campaigns", "Sold property posts"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "facebook-ads-for-real-estate-agents": {
    slug: "facebook-ads-for-real-estate-agents",
    keyword: "Facebook ads for real estate agents",
    title: "Facebook Ads for Real Estate Agents",
    h1: "Get buyer and seller leads from one smart campaign",
    audience: "Real estate agents",
    industry: "real-estate",
    pain: "Hard to create local lead campaigns consistently",
    cta: "Build a lead campaign",
    useCases: ["Buyer lead ads", "Seller lead ads", "Open house promotion", "Listing showcase"],
    relatedLinks: [
      { label: "AI Marketing Agent for Real Estate", href: "/ai-marketing-agent-for-real-estate" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-agent-for-dentists": {
    slug: "ai-marketing-agent-for-dentists",
    keyword: "AI marketing agent for dentists",
    title: "AI Marketing Agent for Dentists",
    h1: "Book more appointments with automated campaigns",
    audience: "Dental clinics",
    industry: "dental",
    pain: "Clinics need steady patient flow without daily marketing work",
    cta: "Create clinic campaign",
    useCases: ["New patient acquisition", "Appointment reminders", "Treatment promotions", "Review generation"],
    relatedLinks: [
      { label: "Facebook Ads for Dentists", href: "/facebook-ads-for-dentists" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "facebook-ads-for-dentists": {
    slug: "facebook-ads-for-dentists",
    keyword: "Facebook ads for dentists",
    title: "Facebook Ads for Dentists",
    h1: "Launch patient acquisition ads in minutes",
    audience: "Dental clinics",
    industry: "dental",
    pain: "Ad setup feels complicated and slow",
    cta: "Build my dental ad",
    useCases: ["New patient offers", "Teeth whitening promos", "Invisalign campaigns", "Emergency dental ads"],
    relatedLinks: [
      { label: "AI Marketing Agent for Dentists", href: "/ai-marketing-agent-for-dentists" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-agent-for-beauty-salons": {
    slug: "ai-marketing-agent-for-beauty-salons",
    keyword: "AI marketing agent for beauty salons",
    title: "AI Marketing Agent for Beauty Salons",
    h1: "Fill empty appointment slots with smart promos",
    audience: "Beauty salons",
    industry: "beauty",
    pain: "Last-minute openings reduce revenue",
    cta: "Create salon campaign",
    useCases: ["Last-minute slot fills", "Seasonal promotions", "Loyalty offers", "New service launches"],
    relatedLinks: [
      { label: "Instagram Marketing for Beauty Salons", href: "/instagram-marketing-for-beauty-salons" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "instagram-marketing-for-beauty-salons": {
    slug: "instagram-marketing-for-beauty-salons",
    keyword: "Instagram marketing for beauty salons",
    title: "Instagram Marketing for Beauty Salons",
    h1: "Create polished posts and offers without a designer",
    audience: "Beauty salons",
    industry: "beauty",
    pain: "Visual content takes too much time",
    cta: "Generate salon posts",
    useCases: ["Before/after posts", "Offer stories", "New product launches", "Staff spotlights"],
    relatedLinks: [
      { label: "AI Marketing Agent for Beauty Salons", href: "/ai-marketing-agent-for-beauty-salons" },
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
    ],
  },
  "ai-marketing-agent-for-gyms": {
    slug: "ai-marketing-agent-for-gyms",
    keyword: "AI marketing agent for gyms",
    title: "AI Marketing Agent for Gyms",
    h1: "Turn fitness offers into local member signups",
    audience: "Gyms",
    industry: "fitness",
    pain: "Membership campaigns need constant testing",
    cta: "Launch gym campaign",
    useCases: ["New member drives", "Class promotions", "Personal training offers", "Challenge campaigns"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "facebook-ads-for-gyms": {
    slug: "facebook-ads-for-gyms",
    keyword: "Facebook ads for gyms and fitness studios",
    title: "Facebook Ads for Gyms",
    h1: "Grow memberships with targeted local ads",
    audience: "Gyms",
    industry: "fitness",
    pain: "Attracting local members with generic ads wastes budget",
    cta: "Build my gym ad",
    useCases: ["Free trial offers", "New year campaigns", "Summer body promos", "Class schedule ads"],
    relatedLinks: [
      { label: "AI Marketing Agent for Gyms", href: "/ai-marketing-agent-for-gyms" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-agent-for-ecommerce": {
    slug: "ai-marketing-agent-for-ecommerce",
    keyword: "AI marketing agent for ecommerce",
    title: "AI Marketing Agent for Ecommerce",
    h1: "Launch product campaigns that actually convert",
    audience: "Ecommerce stores",
    industry: "ecommerce",
    pain: "Managing ads across channels takes a full team",
    cta: "Create product campaign",
    useCases: ["Product launch ads", "Retargeting campaigns", "Sale promotions", "Abandoned cart emails"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
    ],
  },
  "facebook-ads-for-ecommerce": {
    slug: "facebook-ads-for-ecommerce",
    keyword: "Facebook ads for ecommerce stores",
    title: "Facebook Ads for Ecommerce",
    h1: "Drive product sales with Facebook campaigns built in minutes",
    audience: "Ecommerce stores",
    industry: "ecommerce",
    pain: "ROAS drops when ads are not refreshed fast enough",
    cta: "Build my product ad",
    useCases: ["Product catalog ads", "Flash sale campaigns", "New arrival announcements", "Bundle promotions"],
    relatedLinks: [
      { label: "AI Marketing Agent for Ecommerce", href: "/ai-marketing-agent-for-ecommerce" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-agent-for-lawyers": {
    slug: "ai-marketing-agent-for-lawyers",
    keyword: "AI marketing agent for lawyers",
    title: "AI Marketing Agent for Lawyers",
    h1: "Get more qualified clients without hiring a marketing firm",
    audience: "Law firms",
    industry: "legal",
    pain: "Legal marketing is expensive and slow to produce",
    cta: "Create legal campaign",
    useCases: ["Consultation lead ads", "Practice area campaigns", "Reputation building posts", "Referral programs"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "ai-marketing-agent-for-accountants": {
    slug: "ai-marketing-agent-for-accountants",
    keyword: "AI marketing agent for accountants",
    title: "AI Marketing Agent for Accountants",
    h1: "Attract new clients during tax season and beyond",
    audience: "Accountants",
    industry: "finance",
    pain: "Accountants spend billable time on marketing instead of clients",
    cta: "Create accounting campaign",
    useCases: ["Tax season promotions", "New client offers", "Bookkeeping service ads", "Year-end campaigns"],
    relatedLinks: [
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-agent-for-personal-trainers": {
    slug: "ai-marketing-agent-for-personal-trainers",
    keyword: "AI marketing agent for personal trainers",
    title: "AI Marketing Agent for Personal Trainers",
    h1: "Fill your client calendar with smart campaigns",
    audience: "Personal trainers",
    industry: "fitness",
    pain: "Building a consistent client base requires non-stop marketing",
    cta: "Build my trainer campaign",
    useCases: ["Transformation challenge ads", "Package promotions", "New client offers", "Online training campaigns"],
    relatedLinks: [
      { label: "AI Marketing Agent for Gyms", href: "/ai-marketing-agent-for-gyms" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-agent-for-mortgage-brokers": {
    slug: "ai-marketing-agent-for-mortgage-brokers",
    keyword: "AI marketing agent for mortgage brokers",
    title: "AI Marketing Agent for Mortgage Brokers",
    h1: "Generate buyer leads before the market moves",
    audience: "Mortgage brokers",
    industry: "finance",
    pain: "Mortgage leads dry up without consistent outreach",
    cta: "Generate mortgage leads",
    useCases: ["First-time buyer campaigns", "Refinance offers", "Rate alert campaigns", "Partner referral programs"],
    relatedLinks: [
      { label: "Facebook Ads for Real Estate Agents", href: "/facebook-ads-for-real-estate-agents" },
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
    ],
  },
  "ai-marketing-agent-for-insurance-agents": {
    slug: "ai-marketing-agent-for-insurance-agents",
    keyword: "AI marketing agent for insurance agents",
    title: "AI Marketing Agent for Insurance Agents",
    h1: "Build a steady pipeline of insurance leads",
    audience: "Insurance agents",
    industry: "insurance",
    pain: "Insurance leads are competitive and expensive",
    cta: "Create insurance campaign",
    useCases: ["Life insurance leads", "Home insurance campaigns", "Business coverage ads", "Renewal campaigns"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "ai-marketing-agent-for-cleaning-services": {
    slug: "ai-marketing-agent-for-cleaning-services",
    keyword: "AI marketing for cleaning services",
    title: "AI Marketing Agent for Cleaning Services",
    h1: "Get more bookings with campaigns that run themselves",
    audience: "Cleaning services",
    industry: "home-services",
    pain: "Cleaning businesses rely on word of mouth and can't scale it",
    cta: "Get more cleaning clients",
    useCases: ["New client offers", "Seasonal deep clean promos", "Commercial cleaning campaigns", "Referral programs"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "WhatsApp Campaign Generator", href: "/tools/whatsapp-campaign-generator" },
    ],
  },
  "ai-marketing-agent-for-tutors": {
    slug: "ai-marketing-agent-for-tutors",
    keyword: "AI marketing for tutors and tutoring centers",
    title: "AI Marketing Agent for Tutors",
    h1: "Grow your student base with campaigns built in minutes",
    audience: "Tutors",
    industry: "education",
    pain: "Tutors rely on parent referrals and can't grow predictably",
    cta: "Create tutoring campaign",
    useCases: ["Exam season promotions", "New subject campaigns", "Group class ads", "Back-to-school offers"],
    relatedLinks: [
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "ai-campaign-builder-for-small-business": {
    slug: "ai-campaign-builder-for-small-business",
    keyword: "AI campaign builder for small business",
    title: "AI Campaign Builder for Small Business",
    h1: "One tool that builds your entire marketing campaign",
    audience: "Small businesses",
    industry: "general",
    pain: "Small businesses jump between too many tools and never finish campaigns",
    cta: "Build my first campaign free",
    subheadline: "Buildo learns your business DNA, creates the campaign assets, and helps you publish across your marketing channels with manual approval.",
    useCases: ["Facebook and Instagram ads", "WhatsApp campaigns", "Email marketing", "Landing pages", "Content calendar"],
    relatedLinks: [
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
      { label: "Buildo vs ChatGPT", href: "/buildo-vs-chatgpt" },
      { label: "Best AI Marketing Tools", href: "/best-ai-marketing-tools-small-business" },
    ],
  },
  "best-ai-marketing-tools-small-business": {
    slug: "best-ai-marketing-tools-small-business",
    keyword: "best AI marketing tools for small business",
    title: "Best AI Marketing Tools for Small Business",
    h1: "The AI marketing tools actually worth your time",
    audience: "Small businesses",
    industry: "general",
    pain: "There are hundreds of AI tools and most don't work together",
    cta: "Try Buildo free",
    subheadline: "Most small businesses don't need more AI tools — they need one AI worker that handles the full campaign workflow end to end.",
    useCases: ["Ad creation", "Campaign planning", "Social content", "WhatsApp automation", "Email marketing"],
    relatedLinks: [
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
      { label: "Buildo vs ChatGPT", href: "/buildo-vs-chatgpt" },
      { label: "Buildo vs Marketing Agency", href: "/buildo-vs-marketing-agency" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "whatsapp-business-automation": {
    slug: "whatsapp-business-automation",
    keyword: "WhatsApp business automation for small business",
    title: "WhatsApp Business Automation",
    h1: "Turn WhatsApp into your best-performing marketing channel",
    audience: "Small businesses",
    industry: "general",
    pain: "Most businesses reply to WhatsApp manually and lose leads overnight",
    cta: "Automate my WhatsApp",
    useCases: ["Lead qualification", "Appointment booking", "Order updates", "Promo broadcasts", "Abandoned cart recovery"],
    relatedLinks: [
      { label: "WhatsApp Campaign Generator", href: "/tools/whatsapp-campaign-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "social-media-marketing-for-small-business": {
    slug: "social-media-marketing-for-small-business",
    keyword: "social media marketing for small business",
    title: "Social Media Marketing for Small Business",
    h1: "A month of social content created in one session",
    audience: "Small businesses",
    industry: "general",
    pain: "Consistent social posting takes time most owners don't have",
    cta: "Create my content plan",
    useCases: ["Monthly content calendar", "Platform-specific posts", "Story ideas", "Hashtag strategy", "Engagement campaigns"],
    relatedLinks: [
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "ai-marketing-for-med-spas": {
    slug: "ai-marketing-for-med-spas",
    keyword: "AI marketing for med spas",
    title: "AI Marketing for Med Spas",
    h1: "Fill treatment slots with high-intent local campaigns",
    audience: "Med spas",
    industry: "beauty",
    pain: "Med spa clients are high-value but hard to reach without consistent ads",
    cta: "Create med spa campaign",
    useCases: ["Botox & filler promotions", "New treatment launches", "Membership campaigns", "Referral programs"],
    relatedLinks: [
      { label: "AI Marketing Agent for Beauty Salons", href: "/ai-marketing-agent-for-beauty-salons" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-for-chiropractors": {
    slug: "ai-marketing-for-chiropractors",
    keyword: "AI marketing for chiropractors",
    title: "AI Marketing for Chiropractors",
    h1: "Attract more patients with campaigns that run automatically",
    audience: "Chiropractors",
    industry: "health",
    pain: "Chiropractic clinics depend on walk-ins and referrals without a reliable system",
    cta: "Create patient campaign",
    useCases: ["New patient specials", "Pain relief campaigns", "Family plan promotions", "Wellness campaigns"],
    relatedLinks: [
      { label: "AI Marketing Agent for Dentists", href: "/ai-marketing-agent-for-dentists" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-for-contractors": {
    slug: "ai-marketing-for-contractors",
    keyword: "AI marketing for contractors and home services",
    title: "AI Marketing for Contractors",
    h1: "Get more job leads without paying for every click",
    audience: "Contractors",
    industry: "home-services",
    pain: "Contractors lose work to competitors with stronger online presence",
    cta: "Get more contractor leads",
    useCases: ["Service area targeting", "Project showcase ads", "Before/after campaigns", "Seasonal offer promotions"],
    relatedLinks: [
      { label: "AI Marketing Agent for Cleaning Services", href: "/ai-marketing-agent-for-cleaning-services" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-for-event-planners": {
    slug: "ai-marketing-for-event-planners",
    keyword: "AI marketing for event planners",
    title: "AI Marketing for Event Planners",
    h1: "Book more events with campaigns that showcase your work",
    audience: "Event planners",
    industry: "events",
    pain: "Event planners need a constant pipeline of corporate and private clients",
    cta: "Create my event campaign",
    useCases: ["Portfolio showcase ads", "Corporate event pitches", "Wedding season campaigns", "Testimonial campaigns"],
    relatedLinks: [
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
      { label: "Facebook Ad Generator", href: "/tools/facebook-ad-generator" },
    ],
  },
  "ai-marketing-for-coaches": {
    slug: "ai-marketing-for-coaches",
    keyword: "AI marketing for coaches and consultants",
    title: "AI Marketing for Coaches",
    h1: "Attract high-ticket clients with campaigns built around your expertise",
    audience: "Coaches",
    industry: "coaching",
    pain: "Coaches struggle to communicate their value in ads and posts",
    cta: "Build my coaching campaign",
    useCases: ["Discovery call campaigns", "Webinar promotions", "Program launches", "Authority content"],
    relatedLinks: [
      { label: "Marketing Plan Generator", href: "/tools/marketing-plan-generator" },
      { label: "AI Campaign Builder for Small Business", href: "/ai-campaign-builder-for-small-business" },
    ],
  },
  "ai-marketing-for-clinics": {
    slug: "ai-marketing-for-clinics",
    keyword: "AI marketing for clinics and healthcare",
    title: "AI Marketing for Clinics",
    h1: "Grow patient volume with compliant, effective campaigns",
    audience: "Clinics",
    industry: "health",
    pain: "Healthcare marketing has compliance requirements that slow everything down",
    cta: "Create clinic campaign",
    useCases: ["New patient acquisition", "Specialty promotions", "Telehealth campaigns", "Seasonal health campaigns"],
    relatedLinks: [
      { label: "AI Marketing Agent for Dentists", href: "/ai-marketing-agent-for-dentists" },
      { label: "AI Marketing for Chiropractors", href: "/ai-marketing-for-chiropractors" },
    ],
  },
};

export const ALL_SLUGS = Object.keys(PAGES_DATA);